/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Index2RouteImport } from './routes/index2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubpathIdRouteImport } from './routes/subpath/$id'

const Index2Route = Index2RouteImport.update({
  id: '/index2',
  path: '/index2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubpathIdRoute = SubpathIdRouteImport.update({
  id: '/subpath/$id',
  path: '/subpath/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index2': typeof Index2Route
  '/subpath/$id': typeof SubpathIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index2': typeof Index2Route
  '/subpath/$id': typeof SubpathIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/index2': typeof Index2Route
  '/subpath/$id': typeof SubpathIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index2' | '/subpath/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index2' | '/subpath/$id'
  id: '__root__' | '/' | '/index2' | '/subpath/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Index2Route: typeof Index2Route
  SubpathIdRoute: typeof SubpathIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index2': {
      id: '/index2'
      path: '/index2'
      fullPath: '/index2'
      preLoaderRoute: typeof Index2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subpath/$id': {
      id: '/subpath/$id'
      path: '/subpath/$id'
      fullPath: '/subpath/$id'
      preLoaderRoute: typeof SubpathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Index2Route: Index2Route,
  SubpathIdRoute: SubpathIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
